version: "2.1"

# TODO what does this do?
services:
  blogo:
    image: blogo
    build: .
    environment:
      NODE_ENV: development
    ports:
      - 3000:3000
      - 9229:9229
    ## set your startup file here
    command: node --inspect index.js
